# Generated by Django 6.1 on 2026-09-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Início')),
                ('hora_fim', models.TimeField(verbose_name='Fim')),
                ('sala', models.CharField(blank=True, max_length=30, verbose_name='Sala')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='diario.disciplina')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_lecionados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='diario.turma')),
            ],
            options={
                'verbose_name': 'Horário de aula',
                'verbose_name_plural': 'Horários de aula',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
