# Generated by Django 6.1 on 2026-09-14 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0002_horarioaula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('recesso', 'Recesso'), ('prova', 'Prova/Avaliação'), ('matricula', 'Período de matrícula'), ('evento', 'Evento')], default='evento', max_length=12)),
                ('data_inicio', models.DateField(verbose_name='Data')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco se o evento durar só um dia.', null=True, verbose_name='Até')),
                ('descricao', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, help_text='Deixe em branco se o evento valer para toda a escola.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='diario.turma')),
            ],
            options={
                'verbose_name': 'Evento do calendário',
                'verbose_name_plural': 'Eventos do calendário',
                'ordering': ['data_inicio'],
            },
        ),
    ]
