# Generated by Django 6.1 on 2026-09-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0002_horarioaula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('corpo', models.TextField(verbose_name='Mensagem')),
                ('publico', models.CharField(choices=[('todos', 'Toda a escola'), ('curso', 'Um curso específico'), ('turma', 'Uma turma específica')], default='todos', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateField(blank=True, help_text='Deixe em branco para não expirar.', null=True, verbose_name='Expira em')),
                ('email_enviado_para', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_publicados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='diario.curso')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='diario.turma')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
