# Generated by Django 6.1 on 2026-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestacaoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('contato', models.CharField(max_length=150, verbose_name='Telefone ou e-mail')),
                ('curso_interesse', models.CharField(max_length=150, verbose_name='Curso técnico de interesse')),
                ('cidade', models.CharField(blank=True, max_length=150, verbose_name='Cidade / bairro')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem (opcional)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Manifestação de interesse',
                'verbose_name_plural': 'Levantamento de demanda',
                'ordering': ['-criado_em'],
            },
        ),
    ]
