# Generated by Django 6.1 on 2026-09-18 21:40

import demanda.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacaointeresse',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True, validators=[demanda.validators.validar_cpf], verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
