# Generated by Django 6.1 on 2026-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contato_responsavel',
            field=models.CharField(blank=True, help_text='Telefone, se o aluno for menor de idade', max_length=100, verbose_name='Contato do responsável'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=10),
        ),
    ]
